### ISSUE TITLE
Use

### ISSUE THREAD

**Issue by aaaaaaaaaygjhkj** [nevermind0001/DFM-Numeracy-hack#1]
can you please show a step-by-step tutorial on how to use it, I've been trying for hours and i seem to not be able to get it to work, it would be grateful
thank you

**Comment by nevermind0001** [comment]
I will be happy to help but it would be better if you could share the error you are encountering.

But please check that:

1.  You have installed the required libraries
2.  You have installed the right version of [chromedriver](https://chromedriver.chromium.org/downloads)
3. The path to chromedriver is correctly inserted in PATH (`PATH = "<PATH TO CHROMEDRIVER>//chromedriver.exe"`)
4. You have inserted username and password correctly in the specified fields

If you are still not able to get it to work please let me know specifying the error you are getting.
